// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXOvwDfirSpnw9FEMW_Xb6QiRGWoWwuCI',
    appId: '1:707104488440:web:3555f897413459749a740d',
    messagingSenderId: '707104488440',
    projectId: 'notesapp-cd90b',
    authDomain: 'notesapp-cd90b.firebaseapp.com',
    storageBucket: 'notesapp-cd90b.appspot.com',
    measurementId: 'G-G9WYGR3CPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlEPivtArnwzcf04FSbWCbn4XB1jyPIK0',
    appId: '1:707104488440:android:91ff31a11358ab739a740d',
    messagingSenderId: '707104488440',
    projectId: 'notesapp-cd90b',
    storageBucket: 'notesapp-cd90b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_7Fl7j9Tt4YHm1T5P6sk9mgHUD1npGgM',
    appId: '1:707104488440:ios:2ac029da2b8d12a59a740d',
    messagingSenderId: '707104488440',
    projectId: 'notesapp-cd90b',
    storageBucket: 'notesapp-cd90b.appspot.com',
    iosBundleId: 'com.example.googlenotes',
  );
}
